TWILIO_ACCOUNT_SID = 'AC1c7a6f255c2df8ec487b6c2fa27087e5'  # Replace with your Twilio Account SID
TWILIO_AUTH_TOKEN = '90491dc87bceeadf608d5c312553a7df'    # Replace with your Twilio Auth Token
TWILIO_PHONE_NUMBER = '+12512209401'  # Replace with your Twilio phone number
EMERGENCY_NUMBER = '+918433135192'  # Replace with your phone number (include country code)